version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.17.1
    commands:
      - cd server
      - npm install
      - npx prisma generate
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'server/dist'
